version: '3.7'

services:
  coder-backend:
    build:
      context: .
    container_name: coder-backend
    restart: always
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    external: true
