// Descomente a linha abaixo caso não tenha o arquivo http-client.env.json configurado
#@HostAddress= http://localhost:8080

@ProductId= 6628fd902fb730e28bbbe701
@CartId= 66999f30497c127ec14b10c6
@UserId= 6631808c2db12267e347951d


### LoginAsAdmin
POST {{HostAddress}}/login
Content-Type: application/json

{
  "email": "adminCoder@coder.com",
  "password": "adminCod3r123"
}

### LoginAsUser
POST {{HostAddress}}/login
Content-Type: application/json

{
  "email": "iugmali@gmail.com",
  "password": "654321"
}

### GetSession
GET {{HostAddress}}/api/sessions/current

### TogglePremium
POST {{HostAddress}}/api/users/premium/{{UserId}}

### GetProducts
GET {{HostAddress}}/api/products

### GetProductsLimited
GET {{HostAddress}}/api/products?limit=1

### GetProductsSortedByPrice
GET {{HostAddress}}/api/products?sort=asc

### GetProductsSortedByPriceDesc
GET {{HostAddress}}/api/products?sort=desc

### GetProductsSortedByPriceDescLimited
GET {{HostAddress}}/api/products?sort=desc&limit=1

### AddInvalidProduct
// Deve retornar status 400
POST {{HostAddress}}/api/products
Content-Type: application/json

{
  "title": "",
  "description": "Nova descrição",
  "code": "P1800",
  "price": 100,
  "status": true,
  "stock": 10,
  "category": "Category 1"
}

### AddProduct
POST {{HostAddress}}/api/products
Content-Type: application/json

{
  "title": "Laptop",
  "description": "Outro produto",
  "code": "p44090246",
  "price": 299,
  "stock": 35,
  "category": "Outra"
}

### UpdateProduct
PUT {{HostAddress}}/api/products/{{ProductId}}
Content-Type: application/json

{
  "title": "Produto atualizado",
  "description": "Milhoes de produtos vendidos. Aproveite!",
  "code": "P8888",
  "price": 300
}

### DeleteProduct
DELETE {{HostAddress}}/api/products/{{ProductId}}


### GetProduct
GET {{HostAddress}}/api/products/{{ProductId}}

### AddCart
POST {{HostAddress}}/api/carts

### GetCart
GET {{HostAddress}}/api/carts/{{CartId}}

### UpdateCart
PUT {{HostAddress}}/api/carts/{{CartId}}
Content-Type: application/json

{
  "products": [
    {
      "product": "{{ProductId}}",
      "quantity": 1
    }
  ]
}

### AddProductToCart
POST {{HostAddress}}/api/carts/{{CartId}}/product/{{ProductId}}

### AddProductToCartWithQuantity
POST {{HostAddress}}/api/carts/{{CartId}}/product/{{ProductId}}
Content-Type: application/json

{
  "quantity": 3
}

### PurchaseProductsFromCart
POST {{HostAddress}}/api/carts/{{CartId}}/purchase

### RemoveProductsFromCart
DELETE {{HostAddress}}/api/carts/{{CartId}}
