GET http://localhost:8080/api/user

###

POST http://localhost:8080/api/user
Content-Type: application/json

{
  "first_name": "Guilherme",
  "last_name": "Almeida"
}

###

GET http://localhost:8080/api/user/1

###

PATCH http://localhost:8080/api/user/3
Content-Type: application/json

{
  "first_name": "João",
  "last_name": "Neves"
}

###

DELETE http://localhost:8080/api/user/1
