GET http://localhost:8080/api/frase

###

POST http://localhost:8080/api/palavras
Content-Type: application/json

{
  "palavra": "Guilherme"
}

###

POST http://localhost:8080/api/palavras
Content-Type: application/json

{
  "palavra": "é"
}

###

POST http://localhost:8080/api/palavras
Content-Type: application/json

{
  "palavra": "desenvolvedor"
}

###

GET http://localhost:8080/api/palavras/1

###

PUT http://localhost:8080/api/palavras/3
Content-Type: application/json

{
  "palavra": "Guilherme"
}

###

DELETE http://localhost:8080/api/palavras/2
